# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 30, 670, 520))
        self.frame.setMinimumSize(QtCore.QSize(670, 520))
        self.frame.setStyleSheet("#frame{\n"
"background-color: rgb(193, 193, 193);\n"
"border-bottom-right-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(193, 193, 193);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setStyleSheet("font: 18pt \"Algerian\";\n"
"border:none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/snow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-top:5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_loginOut = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_loginOut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_loginOut.setIcon(icon1)
        self.pushButton_loginOut.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_loginOut.setObjectName("pushButton_loginOut")
        self.horizontalLayout_3.addWidget(self.pushButton_loginOut, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.frame_6, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setStyleSheet("#frame_8{\n"
"background-color: rgb(0, 85, 127);\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"}\n"
".QPushButton{\n"
"border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"Algerian\";\n"
"}\n"
".QPushButton:pressed{\n"
"padding-top:5px;\n"
"}\n"
".QPushButton:hover{\n"
"color: rgb(184, 184, 184);\n"
"}\n"
"\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_home = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_home.sizePolicy().hasHeightForWidth())
        self.pushButton_home.setSizePolicy(sizePolicy)
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_2.addWidget(self.pushButton_home)
        self.pushButton_web = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_web.sizePolicy().hasHeightForWidth())
        self.pushButton_web.setSizePolicy(sizePolicy)
        self.pushButton_web.setObjectName("pushButton_web")
        self.verticalLayout_2.addWidget(self.pushButton_web)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButton_my = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_my.sizePolicy().hasHeightForWidth())
        self.pushButton_my.setSizePolicy(sizePolicy)
        self.pushButton_my.setObjectName("pushButton_my")
        self.verticalLayout_2.addWidget(self.pushButton_my)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"background-color: rgb(193, 193, 193);\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setMinimumSize(QtCore.QSize(167, 50))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25pt \"Algerian\";\n"
"border:1px solid blue;\n"
"border-radius:5px")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page_home)
        self.page_web = QtWidgets.QWidget()
        self.page_web.setObjectName("page_web")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_web)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.page_web)
        self.frame_9.setMaximumSize(QtCore.QSize(300, 400))
        self.frame_9.setStyleSheet(".QPushButton{\n"
"border:2px solid black;\n"
"border-radius:5px;\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"background-color: rgb(132, 132, 132);\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_bilibili = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_bilibili.setMinimumSize(QtCore.QSize(100, 25))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/Bilibili-B站.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_bilibili.setIcon(icon4)
        self.pushButton_bilibili.setObjectName("pushButton_bilibili")
        self.verticalLayout_5.addWidget(self.pushButton_bilibili)
        self.pushButton_tengxun = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_tengxun.setMinimumSize(QtCore.QSize(100, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/TencentVideo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_tengxun.setIcon(icon5)
        self.pushButton_tengxun.setObjectName("pushButton_tengxun")
        self.verticalLayout_5.addWidget(self.pushButton_tengxun)
        self.pushButton_apple = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_apple.setMinimumSize(QtCore.QSize(100, 25))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/apple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_apple.setIcon(icon6)
        self.pushButton_apple.setObjectName("pushButton_apple")
        self.verticalLayout_5.addWidget(self.pushButton_apple)
        self.pushButton_csdn = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_csdn.setMinimumSize(QtCore.QSize(100, 25))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/csdn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_csdn.setIcon(icon7)
        self.pushButton_csdn.setObjectName("pushButton_csdn")
        self.verticalLayout_5.addWidget(self.pushButton_csdn)
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.page_web)
        self.page_my = QtWidgets.QWidget()
        self.page_my.setObjectName("page_my")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_my)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.page_my)
        self.frame_10.setMaximumSize(QtCore.QSize(300, 400))
        self.frame_10.setStyleSheet("QLineEdit{\n"
"background-color: rgba(255, 255, 255,0);\n"
"border:none;\n"
"border-bottom:1px solid black;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-right:5px;\n"
"}\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_newPwd = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_newPwd.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_newPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_newPwd.setObjectName("lineEdit_newPwd")
        self.verticalLayout_6.addWidget(self.lineEdit_newPwd)
        self.lineEdit_newPwd2 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_newPwd2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_newPwd2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_newPwd2.setObjectName("lineEdit_newPwd2")
        self.verticalLayout_6.addWidget(self.lineEdit_newPwd2)
        self.pushButton_submit = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_submit.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.verticalLayout_6.addWidget(self.pushButton_submit)
        self.horizontalLayout_6.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.page_my)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_4.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "home"))
        self.pushButton_home.setText(_translate("MainWindow", "首页"))
        self.pushButton_web.setText(_translate("MainWindow", "网址推荐"))
        self.pushButton_my.setText(_translate("MainWindow", "我的"))
        self.label.setText(_translate("MainWindow", "欢迎来到我的主页"))
        self.pushButton_bilibili.setText(_translate("MainWindow", "哔哩哔哩"))
        self.pushButton_tengxun.setText(_translate("MainWindow", "腾讯视频"))
        self.pushButton_apple.setText(_translate("MainWindow", "apple"))
        self.pushButton_csdn.setText(_translate("MainWindow", "CSDN"))
        self.lineEdit_newPwd.setPlaceholderText(_translate("MainWindow", "新密码:"))
        self.lineEdit_newPwd2.setPlaceholderText(_translate("MainWindow", "确认新密码:"))
        self.pushButton_submit.setText(_translate("MainWindow", "提交"))
import res
